# Generated by Django 3.0 on 2019-12-05 15:08

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='long_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='short_url',
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(blank=True, max_length=512, verbose_name='Long URL')),
                ('short_url', models.CharField(blank=True, max_length=256, unique=True, verbose_name='Short URL')),
                ('creation_time', models.IntegerField(default=time.time, verbose_name='Creation Time')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortener_client.Client')),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
                'db_table': 'client_url',
            },
        ),
    ]
