# Generated by Django 3.0 on 2019-12-06 09:17

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener_client', '0002_auto_20191205_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=60, verbose_name='Agent')),
                ('time', models.IntegerField(default=time.time, verbose_name='Time')),
                ('cookie', models.CharField(blank=True, max_length=256, verbose_name='Cookie')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener_client.Url')),
            ],
            options={
                'verbose_name': 'Viewer',
                'verbose_name_plural': 'Viewers',
                'db_table': 'analytics_viewer',
            },
        ),
    ]
