# Generated by Django 3.0 on 2019-12-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_viewers', models.IntegerField(default=0)),
                ('total_mobile_viewers', models.IntegerField(default=0)),
                ('total_desktop_viewers', models.IntegerField(default=0)),
                ('total_firefox_viewers', models.IntegerField(default=0)),
                ('total_chrome_viewers', models.IntegerField(default=0)),
                ('total_opera_viewers', models.IntegerField(default=0)),
                ('total_ie_viewers', models.IntegerField(default=0)),
                ('total_viewers_by_uid', models.IntegerField(default=0)),
                ('total_mobile_viewers_by_uid', models.IntegerField(default=0)),
                ('total_desktop_viewers_by_uid', models.IntegerField(default=0)),
                ('total_firefox_viewers_by_uid', models.IntegerField(default=0)),
                ('total_chrome_viewers_by_uid', models.IntegerField(default=0)),
                ('total_opera_viewers_by_uid', models.IntegerField(default=0)),
                ('total_ie_viewers_by_uid', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
                'db_table': 'analytics_statistics',
            },
        ),
        migrations.RenameField(
            model_name='viewer',
            old_name='cookie',
            new_name='uid',
        ),
    ]
