# Generated by Django 3.0 on 2019-12-06 11:30

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_analytics', '0002_auto_20191206_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='time',
            field=models.IntegerField(default=time.time, verbose_name='Time'),
        ),
    ]
