# Generated by Django 3.0 on 2019-12-06 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_client', '0002_auto_20191205_1508'),
        ('shortener_analytics', '0003_statistics_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shortener_client.Url'),
        ),
    ]
